# For more information: https://laravel.com/docs/sail
version: '3'
services:
    db:
        image: postgres:12.4
        environment:
            - POSTGRES_PASSWORD=db
            - POSTGRES_USER=db
            - POSTGRES_DB=db
        ports:
            - ${POSTGRES_ADDRESS:-127.0.0.1:5432}:5432